### ISSUE TITLE
Replace preprocessing script

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#1]
(Копия вот этого https://github.com/ods-ai-ml4sg/proj_news_viz/issues/125)
Нужно заменить в пайплайне скрипт препроцессинга и убедиться, что всё работает.
Скрипт есть готовый https://github.com/ods-ai-ml4sg/proj_news_viz/blob/master/nlp/news_viz/data/preprocessing_tools.py

По шагам:
1. Перенести скрипт указанный по ссылке на место такого же в папке `newsviz`
2. Убедиться, что оно не валится на импорте
3. Убедиться, что оно не валится на запуске
Как запустить: [см. инструкцию]( https://github.com/newsviz/newsviz/wiki/Инструкция-по-запуску). Нам нужен только `PreprocessorTask` поэтому заменяем `TopicPredictorTask` на `PreprocessorTask` в команде из инструкции.
4. Проверить, что результат корректный.
5. Закоммитить и сделать PR.

Всё правильно, если
1. Выполняется до конца без ошибок
2. Для каждого входного файла получается выходной файл, соответствующий [инструкции](  https://github.com/newsviz/newsviz/wiki/Инструкция-по-запуску)

**Comment by OlgaCh** [comment]
Можно заняться этой задачей?

**Comment by iggisv9t** [comment]
Можно, конечно. Я в соседнем issue ответил ещё подробнее.

**Comment by vtrokhymenko** [comment]
>Перенести скрипт указанный по ссылке на место такого же в папке pipeline

а разве не в директории `pipeline` обработка должна вызываться с `src`?

**Comment by iggisv9t** [comment]
Это я скопипастил со старой репы невнимательно. Сейчас поправлю.

**Comment by iggisv9t** [comment]
#17
