### ISSUE TITLE
Протестировать визуализацию на Streamlit

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#100]
У нас есть два варианта визуализации. Одна старая добрая на plotly, другая более свежая на streamlit. Когда я в последний раз запускал вторую, там что-то пошло не так. Нужно проверить, описать проблемы при запуске и сделать Issue чтобы кто-то потом пофиксил запуск.
https://github.com/newsviz/newsviz/tree/stage/newsviz/visualizer

**Comment by vvssttkk** [comment]
протестировал, все запускается
как запустить описал в https://github.com/newsviz/newsviz/wiki/Инструкция-по-запуску#Через-streamlit
![image](https://user-images.githubusercontent.com/8581044/128604510-f9ac8329-8d67-4af6-b158-5d5f88503f11.png)

**Comment by iggisv9t** [comment]
#105 
Шик. Надо бы там только подправить ширину и выравнивание.

**Comment by vvssttkk** [comment]
> #105
> Шик. Надо бы там только подправить ширину и выравнивание.

пытался, сходу не получилось
