### ISSUE TITLE
обновить ./github/wokflows/

### ISSUE THREAD

**Issue by vvssttkk** [newsviz/newsviz#102]
- [x] `ci.yml`
    * разбить `pre-commit-pytests` на 2 отдельные (`pre-commit` и `pytests`)
    * выполнять для всех веток и pr's
    * добавить py36 если в документации написано что работаем с `3.6+`
    * добавить `timeout-minutes`
- [x] `codeql-analysis.yml`
    * ~заменить название на `codeql.yml`~
    * запускать только для `master`
- [x] `pre-commit-config.yaml`
    * раскомментировать `additional_dependencies` в 
    * выполнить `pre-commit autoupdate`

**Comment by iggisv9t** [comment]
Не понял почему надо stage убрать из проверок, если все изменения в первую очередь туда? Чтобы комитить, комитить, а потом перед мёржем в мастер обнаруживать, что там что-то не так?

**Comment by vvssttkk** [comment]
stage решил убрать только в codeql, тк он долго отрабатывает и зря кушает время
а в ci зацепил совершенно случайно, сейчас добавлю

**Comment by iggisv9t** [comment]
#104
