### ISSUE TITLE
попытаться запустить `newsviz/pipeline.py` и отписать что не так

### ISSUE THREAD

**Issue by vvssttkk** [newsviz/newsviz#106]

**Comment by vvssttkk** [comment]
согласно #105 запустил
```
PYTHONPATH='.' luigi --module pipeline TopicPredictorTask --conf=../config/config.ini --local-scheduler
```
и получил след ошибки 
![image](https://user-images.githubusercontent.com/8581044/128626346-235a8e74-294a-4a26-9e51-0f28f3beb9fe.png)

когда запустил отдельно `PreprocessorTask` вроде как все отработало, но папки в `data` ничем не заполнились 
![image (1)](https://user-images.githubusercontent.com/8581044/128626381-3c8cf6ea-c4c0-4102-a154-744c2fb73813.png)

**Comment by iggisv9t** [comment]
Не закрываю, потому что туда добавилось теперь
- [x] вернуть `classnames_gazeta.json` обратно в `classnames.json` потому что оно не должно быть завязано на конкретные имена. Вообще лучше даже в конфиг имя файла пихать, конечно, но в любом случае не хардкодить.
- [x] убрать `.gitkeep` из поддиректорий `data`, потому что оно теперь не обязательно так называется и генерится скриптом вместе с конфигом.

**Comment by iggisv9t** [comment]
Инициализация проекта скриптом оказалась снова с багом. Там был потерян кусок конфига для классификатора. Скоро запушу обновление.
