### ISSUE TITLE
Добавить .gitignore и requirements.txt

### ISSUE THREAD

**Issue by VladislavNekto** [newsviz/newsviz#14]
Без них будет не удобно.

**Comment by iggisv9t** [comment]
`requirements.txt` собираем через https://github.com/bndr/pipreqs и не в коем случае не через `pip freeze`
Задача: состряпать requirements.txt и положить в корень проекта.

**Comment by vtrokhymenko** [comment]
и версии лучше все же фиксировать

**Comment by iggisv9t** [comment]
Про версии -- это большая тема, и наверное простого правильного подхода нет. Нам надо либо следить за тем, чтобы версии были актуальные, и где можно ставить >= а где ==, либо предупреждать, что лучше завести отдельное окружение под проект, потому что он может задаунгрейдить половину пакетов. Я бы выбирал вариант исходя из случая, что про requirements.txt забыли надолго и надо, чтобы при этом ничего сильно не ломалось.

**Comment by iggisv9t** [comment]
#15
