### ISSUE TITLE
Сделать путь к файлам для визуализации параметром

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#19]
https://github.com/newsviz/newsviz/blob/6880b5a04a49ffc2f3548cb7008c6cefe0f53d2f/newsviz/visualizer/app.py#L22
Сейчас путь указан прямо в коде. Нужно, чтобы оно принимало путь к конфигурационному файлу, и читало данные оттуда. Соответственно надо поменять шаблонный конфигурационный файл `/config/config.ini` и по умолчанию путь для визуализации должен быть в `/data/ready2viz`

**Comment by iwooloowi** [comment]
У нас сейчас в конфиг файле пути задаются относительно, например `raw_path = ../data/raw/`. Я так понял, что это для того, чтобы запускать скрипты непосредственно из той же папки где они находятся. Я в визуализаторе сделал также, но с еще одним уровнем вложенности это уже не очень смотрится -- `data_path = ../../data/ready2viz`. Может быть, задавать пути без `../..`, и скрипты запускать из корня проекта?

**Comment by iggisv9t** [comment]
Ну тогда для луиджи команда усложнится. Предполагается, что в итоге будет `run.py` где всё это прописывается один раз, а не в терминале команды городить в три строки.

**Comment by iggisv9t** [comment]
#23
