### ISSUE TITLE
Фильтрация директорий в тасках пайплайна

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#2]
Исходник тут https://github.com/newsviz/newsviz/blob/master/newsviz/pipeline.py
Проблема вот в таких кусках в каждой задаче:
```
# TODO: check if is file
self.fnames = os.listdir(self.input_path)
```
Если кроме директорий в input_path будут лежать директории, то всё сломается. Нужно добавить фильтрацию, чтобы в `self.fnames` попадали только файлики нужного формата, то есть проверять, что расширение `.csv.gz`.

Изменение добавить во все таски, протестировать, что всё запускается и выполняется.

**Comment by OlgaCh** [comment]
@iggisv9t занялась бы этой задачей в рамках hacktoberfest.

**Comment by iggisv9t** [comment]
Да, конечно. Пока у нас нет предобученных моделей, проблематично проверить пайплайн целиком. Я сегодня ещё напилю задач, чтобы предобученные модели появились. В крайнем случае свои кривые модельки закину, чтобы было на чём гонять.

**Comment by VladislavNekto** [comment]
@iggisv9t, 
> Если кроме директорий в input_path будут лежать директории
Что это значит? Как понимаю, кроме файлов? Почему нельзя просто сделать проверку os.path.isdir?

**Comment by iggisv9t** [comment]
> Почему нельзя просто сделать проверку os.path.isdir? 

Потому что ожидаются файлы csv.gz а не произвольные файлы.

**Comment by VladislavNekto** [comment]
@iggisv9t, я так и не понял, почему нельзя сделать что-то типа:
```python
fnames = []
for item in os.listdir(self.input_path):
    if os.path.isdir(item) or not item.endswith(".csv.gz"):
         continue
    fnames.append(item)
self.fnames = fnames
```
Ведь так мы отсечем все НЕ .csv.gz.

**Comment by VladislavNekto** [comment]
Если я вас правильно понял, то вот [пулл реквест](https://github.com/newsviz/newsviz/pull/13).

**Comment by iggisv9t** [comment]
#13 решает задачу.
