### ISSUE TITLE
Перевести визуализатор с групп по year month на общий datetime

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#20]
https://github.com/newsviz/newsviz/blob/6880b5a04a49ffc2f3548cb7008c6cefe0f53d2f/newsviz/visualizer/utils.py#L45

https://github.com/newsviz/newsviz/blob/6880b5a04a49ffc2f3548cb7008c6cefe0f53d2f/newsviz/visualizer/utils.py#L50-L52

Там есть такая ерунда. Вот надо чтобы предполагалось, что df сразу содержит datetime колонку (название datetime и тип datetime).
Добавить докстринг об этом и проверку, что всё в ожидаемом формате.
После этого  надо поменять инструкцию в `/newsviz/visualizer/readme.md`

**Comment by vtrokhymenko** [comment]
> [...] надо чтобы предполагалось, что df сразу содержит datetime колонку (название datetime и тип datetime).

через https://github.com/CedricFR/dataenforce будет удобнее решить это

**Comment by iggisv9t** [comment]
Надо либо сразу в весь проект это внедрять, либо не тащить ради двух строчек ещё одну зависимость.

**Comment by vtrokhymenko** [comment]
> Надо либо сразу в весь проект это внедрять

а что мешает? это же касается и typing-a
нужно просто начать это применять и при code-review править по надобности

**Comment by iggisv9t** [comment]
> а что мешает?  

Просто надо держать минимум зависимостей и по возможности обходиться стандартными средствами, пока это не станет болезненно. Умножение разных сущностей создаёт много возможностей для разных проблем, и может быть причиной работы, которой можно было бы не делать. Плюс нужно держать низкий порог входа, а любой инструмент -- даже простой, нужно осваивать. Поэтому я бы подождал момента, когда появятся проблемы с которыми dataenforce сделает жизнь сильно лучше, чем без него.

**Comment by iggisv9t** [comment]
#39
