### ISSUE TITLE
Выбор уровня агрегации по дате в визуализации: агрегатор

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#21]
Нужно для выполнения другого ишью. 
Связано с #20 но ждать его закрытия не обязательно.

- [x] Сделать функцию агрегации (этот ишью)
- [ ] Сделать выбор уровня агрегации в dash (будет в другом ишью)

## Сделать функцию агрегации
https://github.com/newsviz/newsviz/blob/6880b5a04a49ffc2f3548cb7008c6cefe0f53d2f/newsviz/visualizer/app.py#L205
Вот тут мы получаем датафрейм, который потом идёт в визуализацию. Колонки датафрейма `datetime,topic_0,topic_1,...`.
Надо уметь делать агрегации по разным временным промежуткам на выбор: month, year, week, day, hour. Соответственно у нас будет функция, которая 
1. принимает описанный выше датафрейм, 
2. принимает уровень агрегации как параметр 
3. и потом делает суммирование по колонкам внутри выбранных промежутков
4. Возвращает датафрейм, где те же колонки с темами + колонку date

Например, если у нас есть
```
df
datetime,topic_0,topic_1
2020-10-10,1,2
2020-10-12,1,2
2020-11-10,3,2
2020-11-12,1,1
```
и агрегация у нас по месяцам, то получим
```
df
date,topic_0,topic_1
2020-10-01,2,4
2020-11-01,3,3
```
Обратите внимание, что если у нас агрегация по месяцам, то мы ставим первое число, а не 0, если по годам, то 1 месяц, а не 0, иначе всё сломается.

Предлагаемый подход (я не знаю, можно ли сделать лучше):
Создаём колонки соответствующие уровню агрегации, например для month это будут year и month
```
df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
```
Потом делаем по ним агрегацию
```
gb = df.groupby(['year', 'month']).agg('sum').reset_index()
```
Потом создаём обратно дату из того, что получили
```
gb["date"] = [
        "{}-{:02d}-01".format(a, b) for a, b in gb[["year", "month"]].values
    ]
```
Возвращаем gb без year и month
Если знаете подход лучше, то делайте лучше.
Функцию пишем в `newsviz/visualizer/utils.py`, вызов в `newsviz/visualizer/app.py` после строки 205.
Сигнатура:
```
def agg_by_time(df, level='month'):
    ...
    return gb
```
## Сделать выбор уровня агрегации в dash
Надо будет сделать пункт меню и callback, чтобы вызывать функцию описанную выше.

**Comment by iwooloowi** [comment]
Через pd.Grouper будет удобнее сделать аггрегацию по времени.

**Comment by iggisv9t** [comment]
О, кайфовенько. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Grouper.html
Тогда это видимо будет как-то так:
`gb = df.groupby(pd.Grouper(key="datetime", freq="1M")).sum()`
А ключи для freq брать отсюда https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases

**Comment by iggisv9t** [comment]
#22
