### ISSUE TITLE
Сделать выбор уровня агрегации в dash

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#22]
Продолжение #21 

- [x]  Сделать функцию агрегации ( #21  )
- [x]  Сделать выбор уровня агрегации в dash (этот ишью)

Считаем, что предыдущий этап закрыт и у нас есть функция agg_by_time(df, level), которая умеет брать датафрейм, и вызывается после вот этого
https://github.com/newsviz/newsviz/blob/6880b5a04a49ffc2f3548cb7008c6cefe0f53d2f/newsviz/visualizer/app.py#L205

Тогда вот здесь нам надо добавить новый `input` меткой пусть будет `agg_level`
https://github.com/newsviz/newsviz/blob/6880b5a04a49ffc2f3548cb7008c6cefe0f53d2f/newsviz/visualizer/app.py#L194-L198
Который будет передаваться в аргумент level, и создать для него дропдаун меню в левой панели.
Что-то вроде того:
```
 html.Div([
            dcc.Markdown(
                d("""
                    **Уровень агрегации**
                """)),
            dcc.Dropdown(
                id="agg_level",
                value='month',
                options=[
                   {"label": "month",
                    "value": "month"}, 
                     {"label": "year",
                    "value": "year"} ...],
            ),
        ]),
```
Примерно вот здесь 
https://github.com/newsviz/newsviz/blob/6880b5a04a49ffc2f3548cb7008c6cefe0f53d2f/newsviz/visualizer/app.py#L114-L115

**Comment by iwooloowi** [comment]
![image](https://user-images.githubusercontent.com/35223471/95776244-9d7cde00-0ccc-11eb-9c6e-6bc195b29418.png)
Если делать группировку чаще, например по дням, то графики выглядят так -- из-за дней, в которых значений нет. Оставлять так, или выбрасывать пропущенные значения?

**Comment by iggisv9t** [comment]
Другие уровни для других данных, более плотных и коротких. Поэтому да, оставлять. Ещё когда-нибудь добавим хитмап, и будет нормально даже с пропусками.

**Comment by iggisv9t** [comment]
#27
