### ISSUE TITLE
add ci/cd

### ISSUE THREAD

**Issue by vtrokhymenko** [newsviz/newsviz#29]
настроить своего рода ci/cd через [github action](https://github.com/features/actions):
- [x] [dependabot](https://dependabot.com/)
- [x] [pre-commit](https://pre-commit.com/)
- [x] [pre-commit-config](https://pre-commit.com/#new-hooks)
- [x] [code scanning](https://github.com/features/security)
- [ ] добавить [pyright](https://github.com/microsoft/pyright)  отдельно в `pre-commit.yml` выполнив генерацию зависимостей и их применение
- [ ] [codefactor](https://www.codefactor.io/)
- [ ] [deepsource](https://deepsource.io/)
- [ ] добавить в `contributing.md` как запускать `pre-commit` (возможно еще упомянуть pyright)

**Comment by iggisv9t** [comment]
Распиши хоть что оно делает и зачем. И почему в проекте Visualizer?

**Comment by vtrokhymenko** [comment]
> Распиши хоть что оно делает и зачем
куда именно то?

> И почему в проекте Visualizer?
показалось что он больше подходит по сравнению с `pipeline`

**Comment by iggisv9t** [comment]
> показалось что он больше подходит по сравнению с pipeline

Проекты не покрывают все задачи, поэтому ни туда, ни сюда.

>  куда именно то?

Ну в ишью прямо. Про то, что за проблемы мы хотим решить добавляя ci/cd.

**Comment by vtrokhymenko** [comment]
> Проекты не покрывают все задачи, поэтому ни туда, ни сюда.

убрать с projects?

**Comment by iggisv9t** [comment]
Я уже сам убрал. Да, пайплайн -- это что делает нам из сырых данных данные для картинок, а визуализация -- то, что рисует получившиеся данные. Если будет сильно много ишью без проекта -- что-то придумаем.

**Comment by iggisv9t** [comment]
Ну честно говоря, на отвяжись объяснение.
![image](https://user-images.githubusercontent.com/19172517/95971462-f0b07700-0e19-11eb-9b00-2b49440ea4a5.png)

Предлагаю разбить этот ишью на много мелких и решать небольшими понятными шагами.

![image](https://user-images.githubusercontent.com/19172517/95971580-12116300-0e1a-11eb-9b4a-b94121cb20a3.png)
Вот такая штука может ответить на вопрос, что это такое, если поковыряться там, но не отвечает на вопрос, зачем оно нам в проекте и какую проблему мы решаем. Ну если бы она одна была бы в ишью и в PR я бы осилил ревью за один подход, а когда целая пачка таких "вот ссылки, почитай там" это затянется.

Мы в старой репе наворотили такого, что никто не может разобраться, поэтому давай тут будем перед каждым изменением подробно расписывать, что оно делает. У меня некоторые ишью длиннее кода, который их закрывает. Потом можно будет легко разобраться, что произошло и как было до этого.
