### ISSUE TITLE
Функция для расчета offset в ridge_plot

### ISSUE THREAD

**Issue by iwooloowi** [newsviz/newsviz#34]
Сейчас в функции ridge_plot используется значение offset (расстояние между линиями на графике), заданное по умолчанию.
https://github.com/newsviz/newsviz/blob/c9aa97c8a0ee8379d56f35c315b2c5cbb4245b97/newsviz/visualizer/utils.py#L145

Это значение было подобрано вручную по тем данным, которые были. На других данных, например при аггрегации не по месяцам, а по годам, график выглядит плохо читаемым.
![FireShot Capture 076 - Dash - 0 0 0 0](https://user-images.githubusercontent.com/35223471/96032191-039d6880-0e67-11eb-92ae-d3c01ec79bb5.png)
Нужно написать функцию, которая будет рассчитывать необходимый offset в зависимости от данных, и передавать это значение в функцию ridge_plot.

**Comment by iggisv9t** [comment]
#39
