### ISSUE TITLE
Проверить и исправить preprocessing

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#43]
https://github.com/newsviz/newsviz/blob/master/newsviz/preprocessing_tools.py
У нас обнаружилось вот такое
![image](https://user-images.githubusercontent.com/19172517/96509969-7f335700-1265-11eb-942f-238c802de4cc.png)

Интернет говорит, что пунктуацию удалять можно быстрее, чем регулярками (может быть найдётся способ даже лучше)
https://www.pythondaddy.com/python/how-to-remove-punctuation-from-a-string-in-python/

Для примера давайте использовать текст вот этой новости https://panorama.pub/50142-vasserman-calvin-klein.html
И символы со скриншота `=, #, $`

Задача такая: добавить приведённые выше символы в список пунктуации, проверить, что всё работает. Если получится, то ускорить очистку и избавиться от одной из регулярок.

**Comment by vtrokhymenko** [comment]
кстати, а где лежит файл `stopwords_ru.txt`?
судя по `newsviz/preprocessing_tools.py` в той же директории, но его там нет

**Comment by iggisv9t** [comment]
Я использовал вот эти https://github.com/ods-ai-ml4sg/proj_news_viz/blob/master/nlp/data/features/stopwords_ru.txt
Вчера посреди ночи писал этот ишью и забыл приложить.
Я очень сомневаюсь насчёт того, стоит ли класть стоп-слова в репозиторий, потому что с ними диффы будут жёсткие, и красивенькая простая структура так начинает распухать. Но так как решения лучше пока никто не предложил, давайте прилагать стоп-слова к модулую препроцессинга, или хостить их где-то и грузить по ссылке. Вроде это должна быть заменяемая вещь. как и входные данные, но в то же время, должен быть вариант по-умолчанию. Ещё, кстати, надо заменить путь к стоп-словам и сделать его параметром. Сейчас запилю отдельный ишью.

**Comment by iggisv9t** [comment]
А не, там, чтобы сделать параметром надо менять способ, которым эта штука вызывается. Проще будет упаковать это в класс, указывать путь к стоп-словам при инстанциировании класса, и тогда в пайплайне придётся поменять пару строк. Тогда позже распишу, что там как сделать.

**Comment by vtrokhymenko** [comment]
не вижу проблем не положить стоп-слова в `data/features` или куда-то в иное место `data`

**Comment by vtrokhymenko** [comment]
+ и положить `path_stop_words` в config

**Comment by tu-artem** [comment]
а есть какая-то причина использовать свой список символов вместо `string.punctuation`? Там вроде всё покрывается и даже чуть больше

**Comment by iggisv9t** [comment]
Нет, никакой особой причины нет. Возможно дело в том, что регулярку писали вручную, а понять, что там не всё было сложно на глаз. Если будет без регулярок и быстрее при этом -- будет лучше.

**Comment by iggisv9t** [comment]
#45
