### ISSUE TITLE
Сохранение словаря BigARTM

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#5]
https://github.com/newsviz/newsviz/blob/master/newsviz/topic_model.py строка 117.
```
    def save_model(self, path):
        """ path: path to save model"""
        # TODO: save dictionary near model
        self.model.save(path)
```
Нужно сохранять словарь, подменяя в path имя файла на `dictionary_` + имя файла + расширение `.txt`. Для этого в bigARTM у словаря есть метод `dictionary.save_text(path)`.

Пример: зовём `tm.save_model(/home/best_contributor/projects/newsviz_files/tm_gazeta.bin)` и получаем в директории `newsviz_files` файлик `tm_gazeta.bin` с моделью и `dictionary_tm_gazeta.txt`

**Comment by rishm069** [comment]
Могу я этим заняться?

**Comment by iggisv9t** [comment]
Да, разумеется.

**Comment by tu-artem** [comment]
Привет, я немного запутался в BigARTM, не могу достать словарь из модели, то есть что-то вроде `self.model.dictionary.save_text()` не работает. Есть какой-то особый способ до него добраться?

Альтернативно, можно отдельно сохранять словарь в атрибуте `TopicModelWrapperARTM`, но не знаю, насколько это эффективно

**Comment by vtrokhymenko** [comment]
> не работает

а выплевывается какая-то ошибка, предупреждение может быть?
какие параметри указывали в `BatchVectorizer()`?
и до этого выполняли что-то по `vowpal_wabbit`?

**Comment by tu-artem** [comment]
artm.version() == '0.9.2'

Делаю примерно следующее:
1. `tm = topic_model.TopicModelWrapperARTM(some_path, source_name)`
2. Загружаю готовую модель и словарь ([отсюда](https://drive.google.com/drive/folders/11KAPsKd5kfF2JvAGSWTQ6RHtLDeLH63-)) через `tm.load_model()`
3. Затем внутри `tm.save_model()` хочу обратиться к словарю, чтобы его сохранить, но не понимаю, как его достать из самой модели artm. Думал, что можно просто что-то вроде `self.model.dictionary` но `AttributeError: 'ARTM' object has no attribute 'dictionary'`, внутри `TopicModelWrapperARTM` словарь вроде тоже нигде не сохраняется

Вопрос скорее в том, как правильно обратиться к словарю из метода `save_model()`

**Comment by vtrokhymenko** [comment]
> как правильно обратиться к словарю из метода save_model()

на вскидку и беглым взглядом через `self.dictionary_path`, который в свою очередь должен заполняться при инициализации класса `TopicModelWrapperARTM`

**Comment by iggisv9t** [comment]
https://github.com/newsviz/newsviz/blob/6880b5a04a49ffc2f3548cb7008c6cefe0f53d2f/newsviz/topic_model.py#L57
Словарь -- это отдельный объект. Тут строка, где он инициируется. Его надо сделать параметром класса, чтобы потом дёрнуть его в другом методе. Возможно из BatchVectorizer его тоже можно достать, но я боюсь, что это не надёжный способ, т.к. bigARTM часто ломают API в таких местах. Но вообще, даже у gensim похожие проблемы бывают, так что придётся с этим жить.

**Comment by iggisv9t** [comment]
#18
