### ISSUE TITLE
Проработать схему будущей БД

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#55]
См #47 
Чтобы переезжать с файликов на базу, нужно установить соглашение, где что лежит. Самый прямолинейный вариант -- продублировать структуру сделанную на файликах, только докинуть везде колонку "источник". То есть под каждый этап своя таблица. Тогда то, что сейчас набор файлов в директории -- будет одной таблицей.

Требования такие:
1. Структура должна требовать как можно меньше изменений в существующем коде (просто потому что так больше шансов довести дело до конца)
2. Выходом будет дока в формате markdown в директории docs (потом прикрутим sphinx) с описанием структуры БД, ожидаемых таблиц и колонок, какой этап что ожидает.

**Comment by Avenon** [comment]
Я еще предлагаю использовать миграции баз данных с использованием `alembic`. Он как раз используется вместе с sqlalchemy.
Нам это поможет поддерживать БД всегда в актуальном состоянии, изменения в структуре бд будут автоматически создаваться (не надо прописывать кучу новых alter'ов). Версионность БД.

**Comment by iggisv9t** [comment]
Можешь описать пример, как нам alembic пригодится? Нам бы сильно много проблем заранее не решать. Вдруг миграции будут происходить раз в версию и конечному пользователю по-барабану?

**Comment by Avenon** [comment]
Конечному пользователю действительно будет по-барабану, т.к. он будет разворачивать базу одним скриптом. Это скорей для разработчиков, кто будет с базой работать полезно.

Пример: Есть таблица, мы в нее пишем данные, потом мы добавили одно новое поле в таблицу и поменяли у существующего тип данных. Делаем миграцию, аппрувим изменения и одной строкой у нас меняется схема базы данных, без необходимости писать sql скрипт alter для изменения таблицы. Плюс если что-то пойдет не так, то с помощью миграции можно без труда откатиться на предыдущую версию БД.

С одной стороны это удобно и правильно. С другой стороны, если мы идем по пути наименьшего сопротивления, то у нас пока будет всего две таблицы. И тут уж особого труда не состовит все вручную обновить.

Пока я вижу структуру так.

1. Минимальная задача:
    Одна таблица `news`, со следующей структой:
    ```
   id - уникальный ключ записи
   source (string) - источник данных. Одно из значений наших датасетов (tass, interfax, rt, rio etc)
   date (datetime) - дата новости
   topic (string) - рубрика новости
   text (string) - текст новости
   created_at (datetime) - дата создания записи
   update_at (datetime) - дата обновления записи (обновляется при каждом update записи)
    ```
   Это минимальный набор, для того, чтобы использовать источник данных из csv файлов (как существующих, так и будущих новых (помнишь я говорил про загрузку историчности?))

2. Будущая задача:
    Эту таблицу нужно будет реализовать, когда будем учить пауков писать в БД.
    Структуру не описываю, но можно взять за основу ту, что пауки делают csv файл.
    Но пока не делать.

Т.е. задача минимум, просто научить препроцессор писать файлы в БД. Как видишь тут не нормализации, ни связей, ни чего. Мне кажется это самый простой вариант для начала.


У меня есть предложение по схлопыванию данных в БД, но думаю, я это предложение в другом issue озвучу.

**Comment by iggisv9t** [comment]
Ты сильно далеко вперёд смотришь. У нас нет таких ресурсов, чтобы решать проблемы, которые мы только предполагаем. Если, конечно, ты не планируешь в одного весь проект дотащить =)

Давай минимально научим препроцессор читать из базы и писать в базу. Просто теперь в пайплайне вместо csv будут таблицы в базе. Надо минимальным количеством изменений текущего решения перебраться к следующему полностью рабочему состоянию, но на БД. Без оптимизаций, без дополнительных штук, которые могут быть полезны в будущем.

**Comment by Avenon** [comment]
Тогда предлагаю самый минимум. Одна таблица со структурой выше, и в нее учим писать сначала из файлов в нашем пайплайне без всяких обработок, миграций.
Это как раз минимальная задача будет. 

А уже после этого будем думать как связать пауков и делать для них вторую табличку для сырых данных.

**Comment by Avenon** [comment]
Описал схему (из одной таблицы) в файле models.py, можно разворачивать БД и смотреть.

**Comment by iggisv9t** [comment]
#77
