### ISSUE TITLE
Переделать PreprocessorTask под sqlalchemy

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#57]
См. #47 
Зависит от #55 но в принципе, можно закрывая этот ишью частично проработать тот.
Требуется внести минимальные изменения (желательно переделать только `output()`, всё, что касается чтения и записи данных и `__init__()`) чтобы `PreprocessorTask` читал данные из базы и писал результат работы обратно в базу.

**Comment by iggisv9t** [comment]
Вообще желательно логику разделить. Сейчас в run происходит чтение, а можно выдернуть чтение в отдельную функцию, а run будет звать какой-нибудь `self.read_data()`.

**Comment by Avenon** [comment]
Инструкция по запуску препроцессинга в БД:
1) Разворачиваем базу:
    - Переходим в каталог newsviz/database
    - Запускаем скрипт `db_create.py`
    ```
    python db_create.py
    ```
2) Запускаем пайплайн:
```
PYTHONPATH='.' luigi --module pipeline DBTransfer  --conf=../config/config.ini --local-scheduler
```
3) Готово, данные из файлов, которые были обработаны из data/raw и сохранены в data/processed, перекочивали в БД (т.е. из data/processed в БД)

**Comment by iggisv9t** [comment]
#77
