### ISSUE TITLE
Схлопывание обработанных новостей для БД

### ISSUE THREAD

**Issue by Avenon** [newsviz/newsviz#62]
Есть предложение записывать в БД данные, группируя по датам и рубрикам, а токены представлять в виде ключ-значения, где ключ это токен, а значение количество вхождений.

Пример.
Исходные данные. 
Сейчас они в таком виде после препроцессинга:
| дата | рубрика           | текст  |
|----|:-------------:| -----:|
| 2020-12-05 | спорт    | теннис футбол зидан |
| 2020-12-05 | спорт   |   зидан футбол футбол |
| 2020-12-05 | москва |    москва погода столица |
| 2020-12-05 | москва |    столица погода синоптик |
| 2020-12-06 | спорт   |   теннис футбол зидан |
| 2020-12-06 | спорт   |   зидан футбол футбол |
| 2020-12-06 | москва |    москва погода столица |
| 2020-12-06 | москва |    столица погода синоптик жаба |

Обработанные данные, в котором они будут лежать в базе:
| дата | рубрика           | текст  |
|----|:-------------:| -----:|
| 2020-12-05 | спорт    | ({'теннис': 1, 'футбол': 3, 'зидан': 2}) |
| 2020-12-05 | москва |  ({'москва': 1, 'погода': 2, 'столица': 2, 'синоптик': 2}) |
| 2020-12-06 | спорт   |  ({'теннис': 1, 'футбол': 3, 'зидан': 2}) |
| 2020-12-06 | москва |  ({'москва': 1, 'погода': 2, 'столица': 2, 'синоптик': 2, 'жаба': 1}) |

Мне кажется такая структура хранения данных уменьшит объем данных, и при этом не потеряется информативность при дальнешейм анализе и визуализации.

**Comment by iggisv9t** [comment]
Это безусловно хорошо и полезно, но давай это оставим на когда-нибудь потом.
Мы можем за несколько минимальных шагов перейти к работе на БД, оно будет работать приемлемо, хоть и не идеально.
Либо мы можем делать оптимизации на каждом шаге, делать накручивать полезных фич, но за то же время ничего полностью рабочего не выйдет. Вот эта штука далеко не единственная оптимизация, которую мы могли бы сделать.

```
Ленивый перфекционист

Никогда не создавайте ничего, что не является точным минимальным решением проблемы, которую мы можем определить и должны решить.

Ленивый перфекционист тратит свое свободное время наблюдая за другими и выявляя задачи, которые нужно решить. Он ищет понимания, всегда спрашивая “В чем реальная проблема?”, затем движется точно и минимально, создавая или заставляя других создавать пригодное для использования решение для одной конкретной задачи. Он использует или поручает другим использовать эти решения, и повторяет это до тех пор, пока не закончатся нерешенные проблемы, или время и деньги.
```

Реальная наша проблема сейчас в том, что с в текущем состоянии проекта неудобно докидывать данные. О производительности работы с БД, которой ещё нет думать рано. Это не корпоративная разработка с условно неограниченным ресурсом, поэтому мы должны очень избирательно делать только самое важно и стараться сохранять проект очень простым, иначе он заглохнет.

**Comment by Avenon** [comment]
Тогда, давай это отложим в какой-нибудь долгий backlog :)

**Comment by iggisv9t** [comment]
Ну возможно уже пора схлопывать. Причём сырые и наверное даже словари отдельно делать, то есть хранить в одном месте словарь "слово": id а вместо самих текстов id: счётчик. Я что-то не ожидал, что так размеры будут раздуваться.

**Comment by iggisv9t** [comment]
#77
