### ISSUE TITLE
Добавить в master версию c docker

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#65]
Новые PR на некоторое время сломают функциональность в стейдже, поэтому предлагаю то, что сейчас есть добавить в мастер, а потом переезжать на БД.

**Comment by vtrokhymenko** [comment]
очень жестко и не особо правильно со стороны разработки
лучше создать еще одну прмежуточную ветку, вроде ничего не мешает
в целом, не работающий функционал в `master` лучше не ложить

**Comment by iggisv9t** [comment]
Так никто не собирается в мастер класть неработающий функционал. Предлагаю прежде чем ломать стейдж, залить рабочее в мастер. Там добавился докер и инструкции по pre-commit. А потом уже на стейдже ломать и чинить. Мастер всегда рабочий остаётся.
