### ISSUE TITLE
Сделать препроцессинг для английского языка

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#67]
1. Нужен английский препроцессинг эквивалентный тому, что сейчас для русского (насчёт лемматизации не ясно, нужна ли она в английском, может быть просто какой-то стемминг впилить)
2. Возможность выбрать в пайплайне какой будет использоваться. Через конфиг -- лучший способ, как я вижу.

**Comment by vvssttkk** [comment]
@iggisv9t этот issues по идее стоит закрыть?

**Comment by iggisv9t** [comment]
Заменили на #80
