### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#68]
- [x] Убрать директорию database. Весь рабочий код должен быть в `newsviz/newsviz`
- [x] Спрятать скрипты `.sh`
- [x] Выкинуть ноутбук с примером. Мы не в основном репозитории жупайтер ноутбуки. В целях документации надо делать директорию docs и в ней писать документы в markdown. Ноутбуки можно наваливать в https://github.com/newsviz/research

**Comment by vvssttkk** [comment]
> Убрать директорию database. Весь рабочий код должен быть в `newsviz/newsviz`

а почему дважды `newsviz`?

**Comment by iggisv9t** [comment]
Потому что когда в обсуждении pr предложили переместить в newsviz Егор решил, что речь идет про корень. Я не знаю как писать, чтобы все одно и то же понимали одинаково. Давайте договоримся, что если что-то кажется непонятным или нелогичным, то надо предполагать объяснение из здравого смысла.

**Comment by vvssttkk** [comment]
то есть, делаем все же через `newsviz/newsviz`?
предлагаю сделать папку `db` (или что-то в этом роде) просто в `newsviz`, так понятно что там будет лежать как минимум

**Comment by iggisv9t** [comment]
Да просто в `newsviz` имелось в виду. Репозиторий `newsviz`, директория `newsviz`. Будет оно там внутри директории ньюзвиз репозитория ньюзвиз в папке db или нет -- не сильно важно. Мне кажется, два файлика отдельно упаковывать нет смысла, т.к. они прямо к пайплайну относятся.

**Comment by iggisv9t** [comment]
Для того, чтобы было понятно, что файлы про базу данных, можно сделать им префикс `db_` например. Лучше, когда дерево директорий не глубокое, иначе сложно что-то найти.

**Comment by iggisv9t** [comment]
#73
