### ISSUE TITLE
Перевести README.md на английский

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#7]
Задача: пометить в начале файла, что перевод на английский будет под русскоязычной версией, в конце, но перед секцией Contributors добавить толстый заголовок о начале англоязычной версии, затем вставить англоязычный перевод.
Прежде чем коммитить, прогнать через [grammarly](https://www.grammarly.com/)

**Comment by AbhayKaushik** [comment]
I would like to work on this issue.

**Comment by iggisv9t** [comment]
Do you know Russian? Because machine translation will not be good here.

**Comment by AbhayKaushik** [comment]
No, I don't. Thanks for the thumbs up though :smile: and apologies for not realizing this earlier.

**Comment by ily123** [comment]
I'd like to do this. I am a native Russian speaker with a solid grasp of English.

**Comment by iggisv9t** [comment]
#12
