### ISSUE TITLE
обновить preprocessing (русский и английский)

### ISSUE THREAD

**Issue by vvssttkk** [newsviz/newsviz#80]
речь пойдет о функционале, что сейчас в `stage`
на сейчас preprocessing состоит из 2х ф-й: `clean_text` и `lemmatize` (не учитывая `get_morph4token` для cache) и работает только для :ru:
хотелось бы добавить и английский язык

пройдемся по отдельным ф-ям

* `clean_text` разбить на 2 языка через if/elif с новым параметром в ф-и `language`, но общую обработку (удаление ссылок, emails итд) оставить для всех языков (пусть выполняется сразу по вызову ф-и). также добавить что вы считаете за нужным для обработки  английского. и 60ю строку перенести под `if` для :ru:

* `lemmatize`
110ю строку заменить на 112, тк она работает только для :ru:
дальше добавить опять таки через if/elif определитель языка для английского и лемматизацию сделать через [spacy](https://spacy.io/usage/linguistic-features#lemmatization); желательно через `@lru_cache()` по подобию ф-и `get_morph4token`
также для английского нужно использовать отдельный файл для стоп-слов

в идеале, это все хорошо бы переделать через класс, как минимум для того, чтобы чтения файла стоп-слов делать только для определённого файла
также путь к стоп-словам добавить в `config.ini` в блок `common`
заодно и тесты на очистку добавить через pytest

ps
стоп-слова можно взять со строго репозитория, вот [тут](https://github.com/ods-ai-ml4sg/proj_news_viz/blob/master/nlp/data/features/stopwords_ru.txt) они
как видно, файл имеет и русские и английские слова. их нужно разбить на 2 отдельных файла 
~также желательно положить в новую папку `features` в каталоге `data`; после обновив `data/readme.md`~

**Comment by vvssttkk** [comment]
@iggisv9t нормально описал?

**Comment by vvssttkk** [comment]
@iggisv9t пересмотри еще раз пжл все ли теперь описано правильно, после нашей общей беседы

**Comment by iggisv9t** [comment]
Да, норм. Если кто-то не разберётся, то поясним.
