### ISSUE TITLE
Реализовать Bump Chart

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#9]
Сейчас нужный файлик находится здесь:
https://github.com/newsviz/newsviz/blob/master/newsviz/visualizer/utils.py

Там есть функция `def bump_chart(df, topics):` вот её нужно реализовать. Ниже закомментированный код, оставшийся от прошлой версии. Можно опираться на него, можно переписать функцию с нуля. Для примера логики можно смотреть функцию `ridge_plot`

На вход приходит датафрейм с колонкой `date` типа `datetime` и колонками со значениями тем. Имена целевых колонок для визуализации передаются вторым аргументом.

Надо возвращать `plotly figure` с графиком изменения рангов тем во времени.
Пример на картинке ниже.
![image](https://user-images.githubusercontent.com/19172517/92136980-5837d780-ee15-11ea-8deb-4493f14e35f9.png)

**Comment by VladislavNekto** [comment]
Где можно взять входные данные для тестирования?

**Comment by iggisv9t** [comment]
Сегодня скину. Спасибо за напоминание.

**Comment by iggisv9t** [comment]
Актуальны ли сами скрипты -- не уверен, но данные лежат в нужных местах и работают как надо (кроме того, что там названия рубрик перепутаны)
https://drive.google.com/file/d/1nIGZyK5w6yGvWLWstPd3eF77y0U8Iv8B/view?usp=sharing

**Comment by iggisv9t** [comment]
#24
